Spring Cleaning: Inspection Data

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [47]:
#read in the data to a pandas dataframe
df = pd.read_csv('Food_Inspections_raw.csv')
df.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location
0,1970470,IYANZE,IYANZE,1909713.0,Restaurant,Risk 1 (High),4623-4627 N BROADWAY,CHICAGO,IL,60640.0,10/28/2016,Short Form Complaint,Pass w/ Conditions,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.966063,-87.657734,"(41.96606299325794, -87.65773412452839)"
1,1970465,KENYATTA'S DAYCARE,KENYATTA'S DAYCARE,2215571.0,Daycare Above and Under 2 Years,Risk 1 (High),2334 E 75TH ST,CHICAGO,IL,60649.0,10/28/2016,License,Pass,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.759085,-87.567448,"(41.75908547586528, -87.56744784945764)"
2,1970461,DOMINOS,DOMINOS,2464564.0,Restaurant,Risk 2 (Medium),1234 S CANAL ST,CHICAGO,IL,60607.0,10/28/2016,Complaint Re-Inspection,Pass,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",41.866277,-87.639360,"(41.86627726994009, -87.63936045226205)"
3,1970431,ST JUDE EDUCATONAL INSTITUTE,ST JUDE EDUCATONAL INSTITUTE,2215504.0,Daycare (2 - 6 Years),Risk 1 (High),2219 E 79TH ST,CHICAGO,IL,60649.0,10/28/2016,License,Pass,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.751569,-87.570283,"(41.75156886294461, -87.57028268677922)"
4,1970429,"FIRST SLICE, LLC",FIRST SLICE,1620340.0,Restaurant,Risk 1 (High),4401 N RAVENSWOOD AVE,CHICAGO,IL,60640.0,10/28/2016,Complaint,Fail,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.961619,-87.673833,"(41.9616193448497, -87.6738326740156)"

In [48]:
#break date into month, year, day
df['month'] = pd.DatetimeIndex(df['Inspection Date']).month
df['day'] = pd.DatetimeIndex(df['Inspection Date']).day
df['year'] = pd.DatetimeIndex(df['Inspection Date']).year

In [49]:
df.Risk.unique()

array(['Risk 1 (High)', 'Risk 2 (Medium)', 'Risk 3 (Low)', 'All', nan], dtype=object)

In [50]:
#recode risk as 1 (high), 2(med), 3(low)

for i in range(len(df)):
    if df.iloc[i,5] == "Risk 1 (High)":
        df.iloc[i,5] = 1
    if df.iloc[i,5] == "Risk 2 (Medium)":
        df.iloc[i,5] = 2
    if df.iloc[i,5] == "Risk 3 (Low)":
        df.iloc[i,5] = 3
    if df.iloc[i,5] == "All":
        df.iloc[i,5] = np.nan

In [51]:
df.Results.unique()

array(['Pass w/ Conditions', 'Pass', 'Fail', 'Not Ready', 'No Entry',
       'Out of Business', 'Business Not Located'], dtype=object)

In [52]:
#recode results as 0 (pass), 1 (pass w conditions), 2 (fail), nan all missing data codes

for i in range(len(df)):
    if df.iloc[i,12] == "Pass":
        df.iloc[i,12] = 0
    if df.iloc[i,12] == "Pass w/ Conditions":
        df.iloc[i,12] = 1
    if df.iloc[i,12] == "Fail":
        df.iloc[i,12] = 2
    if df.iloc[i,12] in ('Not Ready', 'No Entry', 'Out of Business', 'Business Not Located'):
        df.iloc[i,12] = np.nan

In [55]:
df.head()

,Inspection ID,DBA Name,AKA Name,License #,Facility Type,Risk,Address,City,State,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,Location,month,day,year
0,1970470,IYANZE,IYANZE,1909713.0,Restaurant,1,4623-4627 N BROADWAY,CHICAGO,IL,60640.0,10/28/2016,Short Form Complaint,1,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.966063,-87.657734,"(41.96606299325794, -87.65773412452839)",10,28,2016
1,1970465,KENYATTA'S DAYCARE,KENYATTA'S DAYCARE,2215571.0,Daycare Above and Under 2 Years,1,2334 E 75TH ST,CHICAGO,IL,60649.0,10/28/2016,License,0,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.759085,-87.567448,"(41.75908547586528, -87.56744784945764)",10,28,2016
2,1970461,DOMINOS,DOMINOS,2464564.0,Restaurant,2,1234 S CANAL ST,CHICAGO,IL,60607.0,10/28/2016,Complaint Re-Inspection,0,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",41.866277,-87.639360,"(41.86627726994009, -87.63936045226205)",10,28,2016
3,1970431,ST JUDE EDUCATONAL INSTITUTE,ST JUDE EDUCATONAL INSTITUTE,2215504.0,Daycare (2 - 6 Years),1,2219 E 79TH ST,CHICAGO,IL,60649.0,10/28/2016,License,0,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.751569,-87.570283,"(41.75156886294461, -87.57028268677922)",10,28,2016
4,1970429,"FIRST SLICE, LLC",FIRST SLICE,1620340.0,Restaurant,1,4401 N RAVENSWOOD AVE,CHICAGO,IL,60640.0,10/28/2016,Complaint,2,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.961619,-87.673833,"(41.9616193448497, -87.6738326740156)",10,28,2016

In [56]:
#drop some columns we probably don't care about, can always get back later
df = df.drop(['Location','City','State','License #','AKA Name'], axis=1)

In [57]:
df.head()

,Inspection ID,DBA Name,Facility Type,Risk,Address,Zip,Inspection Date,Inspection Type,Results,Violations,Latitude,Longitude,month,day,year
0,1970470,IYANZE,Restaurant,1,4623-4627 N BROADWAY,60640.0,10/28/2016,Short Form Complaint,1,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.966063,-87.657734,10,28,2016
1,1970465,KENYATTA'S DAYCARE,Daycare Above and Under 2 Years,1,2334 E 75TH ST,60649.0,10/28/2016,License,0,"34. FLOORS: CONSTRUCTED PER CODE, CLEANED, GOO...",41.759085,-87.567448,10,28,2016
2,1970461,DOMINOS,Restaurant,2,1234 S CANAL ST,60607.0,10/28/2016,Complaint Re-Inspection,0,"35. WALLS, CEILINGS, ATTACHED EQUIPMENT CONSTR...",41.866277,-87.639360,10,28,2016
3,1970431,ST JUDE EDUCATONAL INSTITUTE,Daycare (2 - 6 Years),1,2219 E 79TH ST,60649.0,10/28/2016,License,0,33. FOOD AND NON-FOOD CONTACT EQUIPMENT UTENSI...,41.751569,-87.570283,10,28,2016
4,1970429,"FIRST SLICE, LLC",Restaurant,1,4401 N RAVENSWOOD AVE,60640.0,10/28/2016,Complaint,2,21. * CERTIFIED FOOD MANAGER ON SITE WHEN POTE...,41.961619,-87.673833,10,28,2016

In [58]:
df.isnull().sum()

Inspection ID          0
DBA Name               0
Facility Type       4452
Risk                  76
Address                0
Zip                  105
Inspection Date        0
Inspection Type        1
Results            16282
Violations         27249
Latitude             479
Longitude            479
month                  0
day                    0
year                   0
dtype: int64

In [59]:
#save the clean version

df.to_csv('Food_Inspections_Clean.csv', index=False)